# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kha5gGOA9EqpVRAcjMOBqQ1NtqDkZ31q
"""

import pandas as pd

baza={
    "FI":[ "Kamol Usmonov", "Shohida Tursunova", "Akmal Karimov", "Nilufar Yo'ldosheva", "Javohir Abdullayev", "Madina Soliyeva", "Sherzod Qodirov", "Dilnoza Rustamova", "Davron Bobonazarov", "Mohira Nurmatova" ],
    "Yoshi":["25", "30", "28", "22", "35", "27", "33", "24", "29", "31" ],
    "Jinsi":["Erkak", "Ayol", "Erkak", "Ayol", "Erkak", "Ayol", "Erkak", "Ayol", "Erkak", "Ayol"],
    "Kasbi":["Quruvchi", "O'qituvchi", "Dasturchi", "Muhandis", "San'atkor", "Fotograf", "Marketing mutaxassisi", "Iqtisodchi", "Jurnalist", "Sog'liqni saqlash xodimi"],
    "Shahri":["Shahar, Tashkent", "Shahar, Samarqand", "Shahar, Buxoro", "Shahar, Farg'ona", "Shahar, Andijon", "Shahar, Namangan", "Shahar, Qo'qon", "Shahar, Nukus", "Shahar, Urganch", "Shahar, Qarshi"]}
mb=pd.DataFrame(baza)
print(mb)

filtr=mb[(mb['Shahri']=='Shahar, Tashkent') & (mb["Jinsi"]=="Erkak")]
print(filtr)